#!/bin/env bash


deps() {
  if ! type -p $1 &> /dev/null 
  then
      echo "'$1' must be installed to run this script."
      exit 126
  fi
}

deps "mix"
deps "podman"
deps "psql"

help() {
  cat <<_EOF
    Helper script for mix projects

    usage: 
      
      dev <command> [<arg> ...]

    commands:

      server                  mix phx.server
      iex                     iex -S mix phx.server

      pg          start       start postgres
      pg          stop        stop postgres
      pg          connect     stop postgres

      image       build       build image
      image       push        push image to registry

      help                    print help
_EOF
}

(( $# < 1 )) && {
    help
    exit 126
}

case "$1" in
    server)
        mix phx.server
        ;;
    iex)
        iex -S mix phx.server
        ;;
    pg | postgres)
        (( $# < 2 )) && {
            help
            exit 126
        }
        case "$2" in
          start)
            podman run \
              -d \
              -p 5432:5432 \
              --rm \
              --replace \
              --name db \
              -v db:/var/lib/postgresql/data \
              -e POSTGRES_PASSWORD="postgres" \
              postgres:14-alpine
            ;;
          stop)
            podman stop -i db && podman rm -i db
            ;;
          connect)
            $PGBIN/psql -h localhost -p 5432 --username postgres ${@:3}
            ;;
          *)
            help
            exit 126
            ;;
       esac
        ;;
    image)
        (( $# < 2 )) && {
            help
            exit 126
        }
        case "$2" in
          build)
            podman build . -t registry.tell.nu/builder.tell.nu
            ;;
          push)
            podman push registry.tell.nu/builder.tell.nu
            ;;
          *)
            help
            exit 126
            ;;
        esac
        ;;
    help)
        help
        ;;
    *)
        help
        exit 126
        ;;
esac

